general:
  data: "UNCDEL006_BRD4.csv"
  lib_size: 850000
  output_dir: "DEL6"

# If indexes are not provided, raw_indexes will be used. If only indexes are provided, SD_min and NSC_values cannot be calculated
# due to the necessity of raw reads for depth. You can still run the analysis, but the top of the report will display NA for these values.
# Control columns are necessary for MLE and Z-scores calculations.
# The id_col is used to specify the identifier column. If DEL_ID is not specified, the first column will be used by default.

id_col: "DEL_ID"
# raw_index2	elution1_corrected_index2	raw_index3	elution1_corrected_index3	raw_index4	elution1_corrected_index4	raw_index6	corrected_index6	raw_index7	elution2_corrected_index7	raw_index8	elution2_corrected_index8	raw_index11	elution2_corrected_index11	raw_index13	corrected_index13

indexes:
  elution1: ["elution1_corrected_index2", "elution1_corrected_index3", "elution1_corrected_index4"]
  elution2: ["elution2_corrected_index7", "elution2_corrected_index8", "elution2_corrected_index11"]

control_cols:
  elution1: ["corrected_D3index6"]
  elution2: ["corrected_D3index13"]

raw_indexes:
  elution1: ["raw_D3index1", "raw_D3index2", "raw_D3index3"]
  elution2: ["raw_D3index4", "raw_D3index5", "raw_D3index6"]

flags:
  SD_min: True
  NSC_values: True
  MLE: True
  Z_score: True
  z_score_log_data: True
  disynthon_data: true
  polyO: True
  trisynthon_overlap: True
  disynthon_overlap: True
  disynthon_threshold: 50
  normalized_data: True
  simple_spotfire_version: true
  ml_fingerprints_to_RF_reg: true
  ml_fingerprints_to_RF_clf: true
  clf_thresh: 7
  gnn_classifier: false
  gnn_threshold: 10
  gnn_arch: "GAT"
  top_hits: 20
  top_hits_metric: "avg" #enter any metric calculated for enumerated library members
  monosynthon_chemical_space: true
  report: true

  top_disynthons:
    enabled: True
    comparison: "control"       # Type of comparison: "control" or "exp2" or "none"
    exp_name: "elution1"
    exp2_name: "elution2"
    control_name: "elution1"
    top_count: 10               # Number of top disynthons to pull
    comparison_metric: "avg"
