name: Check Docs

on:
  pull_request:
    branches:
      - main
  release:
    types:
      - created

jobs:
  check-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install --with docs

      - name: Build docs
        run: sphinx-build docs docs/_build/html
